server:
  port: 8100
spring:
  application:
    name: Y-service
  profiles:
    active: private
  cache:
    type: redis


  # RabbitMQ配置
  rabbitmq:
    host: ${yilena.mq.host}
    port: 5672
    username: ${yilena.mq.username}
    password: ${yilena.mq.password}
    virtual-host: /
    # 连接池配置
    connection-timeout: 5000
    cache:
      channel.size: 50
      channel.checkout-timeout: 1000
    # 消息确认机制
    publisher-returns: true



  # 配置MySQL数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${yilena.database.url}
    username: ${yilena.database.username}
    password: ${yilena.database.password}


  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  # 配置Redis连接信息
  data:
    redis:
      host: ${yilena.redis.host}
      port: ${yilena.redis.port}
      database: ${yilena.redis.database}

# 配置MyBatis日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置阿里云OSS对象存储服务
aliyun:
  oss:
    endpoint: ${yilena.oss.endpoint}
    bucketName: ${yilena.oss.bucketName}
    region: ${yilena.oss.region}


jwt:
  secretKey: ${yilena.jwt.secretKey}
  expire: ${yilena.jwt.expire}

elasticSearch:
  host: ${yilena.elasticSearch.host}

# 雪花算法配置
sf:
  work-i-d: 3
  #序列号长度
  sequence-length: 6
  #数据中心位移移 位数
  data-center-index: 6
  #机器ID位移移 位数
  work-i-d-index: 8
  #时间戳位移移 位数
  time-stamp-index: 12

